const spot = [
    {
        id: 1,
        name:'ARKOSE',
        number: 33,
        street: 'Rue du Progrès',
        zipcode: 93100,
        city: 'Montreuil',
        country:'France',
        longitude: '',
        latitude: '',
        discipline: 'Rocher',
        type: 'Salle',
        rock_type:'synthétique',
        picture: 'https://www.grimper.com/media/guide_salles/img_salles/arkose_montreuil_5_arkose.jpg',
        various: 'lorem impsum lorem carium',
        reputation: 5,
        min_difficulty: '5a',
        max_difficulty: '9a',
    },
    {
        id: 2,
        name:'Art Bloc.',
        number: 23,
        street: 'Avenue Auguste Verola',
        zipcode: 06200,
        city: 'Nice',
        country:'France',
        longitude: '',
        latitude: '',
        discipline: 'Rocher',
        type: 'Salle',
        rock_type:'Synthétique',
        picture: '',
        various: 'lorem impsum lorem carium',
        reputation: 4,
        min_difficulty: '6d',
        max_difficulty: '9b',
    },
    {
        id: 3,
        name:'Fontainebleau-Les trois pignons',
        number: 8,
        street: 'sentier des belvédères',
        zipcode: 77123,
        city: 'Noisy-sur-ecole',
        country:'France',
        longitude: '153.188.299',
        latitude: '789.258.365',
        discipline: 'Rocher',
        type: 'Spot',
        rock_type:'craie',
        picture: 'https://www.montagnes-magazine.com/media/actu/2020/05/jef-willemyns-mluUYXoTotY-unsplash.jpg',
        various: 'lorem impsum lorem carium',
        reputation: 3,
        min_difficulty: '5c',
        max_difficulty: '8a',
    },
    {
        id: 4,
        name:'BIBEMUS Les carrières de Cézanne',
        number: 3080,
        street: 'Chem. de Bibémus',
        zipcode: 13100,
        city: 'Aix-en-Provence',
        country:'France',
        longitude: '43.53074657951234',
        latitude: '5.499217430680994',
        discipline: 'Rocher',
        type: 'Spot',
        rock_type:'Grès',
        picture: 'https://www.blockout.fr/images/articles/Nantes.jpg',
        various: 'Site de bloc "style pan", c\'est à nous d\'inventer les blocs, prises taillées en nombre',
        reputation: 2,
        min_difficulty: '3a',
        max_difficulty: '7a',
    },
    {
        id: 5,
        name:'The Roof - Maison de l\'Escalade - Pays Basque',
        number: 3,
        street: 'Pl. André Emlinger',
        zipcode: 64100,
        city: 'Bayonne',
        country:'France',
        longitude: '',
        latitude: '',
        discipline: 'rocher',
        type: 'Salle',
        rock_type:'synthétique',
        picture: 'https://www.grimper.com/media/guide_salles/img_salles/the_roof_pays_basque2.jpg',
        various: 'lorem impsum lorem carium',
        reputation: 2,
        min_difficulty: '5a',
        max_difficulty: '9a',
    },


]
